module swd_version

! Do not edit this file!!!
! This file is made by running 'version_definition.py' in the root directory.

character(len=*), parameter :: version = '1.0.1-alpha.0'

end module swd_version
